name: CI
on: [push, pull_request]
jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: lint
      uses: james-garriss/github-action-psscriptanalyzer@master
      with:
        sendComment: true
        failOnErrors: true
        failOnWarnings: true
        failOnInfos: false
        repoToken: ${{ secrets.GITHUB_TOKEN }}
